<?xml version="1.0"?>
<!-- 
	Transform HL7 Reference Information Model (RIM) Datatypes as modeled by 
	Samson Tu (Stanford University) into a W3C OWL ontology compatible with RIM
	model generated by rim2owl.xsl
     
     Copyright(c) 2005 Alessio Carenini <carenini@gmail.com>     

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.
     
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
     
     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

-->
<xsl:stylesheet version="1.0" 
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
	xmlns:hl7_dt="http://veggente.berlios.de/ns/RIMDatatype#"
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:RIMDatatype="http://veggente.berlios.de/ns/RIMDatatype#"
	xmlns:protege="http://protege.stanford.edu/plugins/owl/protege#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	>
	<xsl:output method="xml" indent="yes" encoding="UTF-8"/>
	<xsl:param name="rim_ns" select="'http://veggente.berlios.de/ns/RIMOntology'"/>
	<xsl:param name="rim_dt" select="'http://veggente.berlios.de/ns/RIMDatatype'"/>
	<!-- TODO 
	List/Vector/Bag types defined in a UML/C++ style cannot be converted into corresponding rdf:IDs
	("<" and ">" are not allowed into a rdf attribute)
	-->
	<xsl:template match="/rdf:RDF">
			<rdf:RDF>
					<xsl:copy-of select="child::node()"/>
					<xsl:apply-templates select="hl7_dt:HL7_Data_Type/hl7_dt:alias"/>
			</rdf:RDF>
	</xsl:template>
	<xsl:template match="hl7_dt:alias">
			<owl:Class>
					<xsl:attribute name="rdf:ID" select="translate(.,'&lt;&gt;','__')"/>
					<owl:equivalentClass>
							<xsl:attribute name="rdf:resource" select="concat($rim_dt,../@rdf:about)"/>
					</owl:equivalentClass>
			</owl:Class>
	</xsl:template>
</xsl:stylesheet>

